# this sample can be invalid

stages:
  - stage: Test
    jobs:
      - job: Unit tests
        steps:
          - step: Step
      - job: Integration tests
        steps:
          - step: Step

  - stage: MoreTests
    dependsOn: []
    jobs:
      - job: More tests
        steps:
          - step: Step

  - stage: BuildApp
    pool: vmss
    dependsOn:
      - MoreTests
      - Test
    jobs:
      - job: Build app
        container: build-image
        steps:
          - step: Step

      - job: Security Scan
        dependsOn: Build app
        steps:
          - step: Step

      - job: Quality Scan
        dependsOn: Build app
        steps:
          - step: Step

  - stage: BuildDatabase
    pool: vmss
    dependsOn:
      - MoreTests
      - Test
    jobs:
      - job: Build database
        container: ssdt
        steps:
          - step: Step

  - stage: DeployToDev
    dependsOn:
      - BuildApp
      - BuildDatabase
    jobs:
      - deployment: DeployApp
        displayName: Deploy app
        environment: 'dev'
        strategy: 
          runOnce:
            deploy:
              steps:
                - step: Deploy app

      - job: DeployDatabase
        displayName: Deploy database
        dependsOn: DeployApp
        steps:
          - step: Deploy database

      - job: Smoke test
        dependsOn:
          - DeployDatabase

  - stage: DeployToProd
    dependsOn: DeployToDev

    jobs:
      - deployment: DeployApp
        displayName: Deploy app
        environment: 'prod'
        strategy: 
          runOnce:
            deploy:
              steps:
                - step: Deploy app

      - job: DeployDatabase
        displayName: Deploy database
        dependsOn: DeployApp
        steps:
          - step: Deploy database

      - job: Smoke test
        dependsOn:
          - DeployDatabase
