# this sample can be invalid

stages:
  - stage: Test
    jobs:
      - job: Unit tests
      - job: Integration tests

  - stage: MoreTests
    dependsOn: []
    jobs:
      - job: Acceptance tests

  - stage: Build
    pool: vmss
    dependsOn:
      - MoreTests
      - Test
    jobs:
      - job: Build app
        container: build-image
      - job: Security Scan
        dependsOn: Build app
      - job: Quality Scan
        dependsOn: Build app
      - job: Build database
        container: ssdt

  - stage: DeployToDev
    dependsOn: Build
    jobs:
      - job: Deploy app
      - job: Deploy database
      - job: Smoke test
        dependsOn: Deploy database

  - stage: DeployToProd
    dependsOn: DeployToDev
    jobs:
      - job: Deploy app
      - job: Deploy database
      - job: Smoke test
        dependsOn: Deploy database
